#!/bin/bash

jupyter labextension install @jupyterlab/git
pip install --upgrade jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
nbdime extensions --enable

jupyter labextension install jupyterlab-drawio

jupyter labextension install jupyterlab-jupytext
pip install jupyterlab_latex
jupyter labextension install @jupyterlab/latex
